### PR TITLE
Make explicit transactions work during tests.

### PR DESCRIPTION
**Pull request by jgoclawski**
Also adds usage examples to README.

---
This change is [Reviewable](https://reviewable.io/reviews/socialwifi/sqlalchemy-postgres-autocommit/3)

### CODE REVIEW

**Comment by jgoclawski** [comment]
@mimo95 @kramarz - review please :)

**Comment by kramarz** [comment]
It's a bit hacky, so it may need some comments (why you assign transaction and who removes it later) in begin method. In general looks good.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 53 at r1](https://reviewable.io:443/reviews/socialwifi/sqlalchemy-postgres-autocommit/3#-Kv3gWvSKMKZmm1qiuDu:-Kv3gWvSKMKZmm1qiuDv:bicdyo1) ([raw file](https://github.com/socialwifi/sqlalchemy-postgres-autocommit/blob/592fb4970d35b458d5c98e1d471c54788645158c/README.md#L53)):*
> ```Markdown
> 
> db.db_session.add(models.User(username="frank"))
> db.db_session.add(models.User(username="bob"))
> ```

I think you should add db.db_session.flush() here so it realy does the sql instructions. Example with explicite transaction does "commit" underneath.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/sqlalchemy-postgres-autocommit/3#-:-Kv3jGIVpP3j9Y4qbOPh:b-hu8q5p)*

**Comment by jgoclawski** [comment]
Actually, no one removed the faked transaction, which was a bug - thanks! 
I've redesigned the PR and the README, to be more explicit. So as it is right now, there's no "autodiscovery" of problematic cases. Instead, there's an option for configuring the session, to let it know that it will have to handle the transaction opened directly on the connection. I hope it is now more verbose. 
Please let me know what you think!

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 53 at r1](https://reviewable.io:443/reviews/socialwifi/sqlalchemy-postgres-autocommit/3#-Kv3gWvSKMKZmm1qiuDu:-Kv8DvxibA_C3uUmfdTR:b-dtkdrq) ([raw file](https://github.com/socialwifi/sqlalchemy-postgres-autocommit/blob/592fb4970d35b458d5c98e1d471c54788645158c/README.md#L53)):*
<details><summary><i>Previously, kramarz (Jakub Skiepko) wrote…</i></summary><blockquote>

I think you should add db.db_session.flush() here so it realy does the sql instructions. Example with explicite transaction does "commit" underneath.
</blockquote></details>

Done, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/socialwifi/sqlalchemy-postgres-autocommit/3#-:-Kv8CjY3HHoJhTxrj5uT:b-yh71by)*

**Comment by jgoclawski** [comment]
Discussed and approved offline by @mimo95.

**Pull request merged**
